name: Prepare Client JS
on:
  push:
    paths:
    - 'client/**'
jobs:
  Minify:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
    - uses: actions/checkout@v2

    - name: Auto Minify
      uses: nizarmah/auto-minify@v2.1
      with:
        overwrite: false
        directory: 'client'

    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS files"
        branch: ${{ github.ref }}
