name: Prepare Client JS
on: [push]
jobs:
  Prepare-Client-JS:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
    - uses: actions/checkout@v2

    - name: Auto Minify
      uses: nizarmah/auto-minify@v2.1
      with:
        overwrite: false
        directory: 'client'

    # Auto commits minified content to the existing files
    # Ignore it if you don't want to commit the files to the repository 
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS files"
        branch: ${{ github.ref }}